// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIG9W84hBycSJwZr86wxpY_lkRq8StZkk',
    appId: '1:63376358868:web:1cd613cda9afe90897ea41',
    messagingSenderId: '63376358868',
    projectId: 'cmsc-23-project-4cdeb',
    authDomain: 'cmsc-23-project-4cdeb.firebaseapp.com',
    storageBucket: 'cmsc-23-project-4cdeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC319c-4_k-T_617jqQMCIToXl9TwgZHzQ',
    appId: '1:63376358868:android:c9107a2b61de1ba497ea41',
    messagingSenderId: '63376358868',
    projectId: 'cmsc-23-project-4cdeb',
    storageBucket: 'cmsc-23-project-4cdeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD28-niHrNP6q2P3Py8th0LfjAHA0DJvb8',
    appId: '1:63376358868:ios:84db4020c37144bf97ea41',
    messagingSenderId: '63376358868',
    projectId: 'cmsc-23-project-4cdeb',
    storageBucket: 'cmsc-23-project-4cdeb.appspot.com',
    iosClientId: '63376358868-ae9lv2i4gui4in24or6olusjeh9d6hnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elgivesv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD28-niHrNP6q2P3Py8th0LfjAHA0DJvb8',
    appId: '1:63376358868:ios:84db4020c37144bf97ea41',
    messagingSenderId: '63376358868',
    projectId: 'cmsc-23-project-4cdeb',
    storageBucket: 'cmsc-23-project-4cdeb.appspot.com',
    iosClientId: '63376358868-ae9lv2i4gui4in24or6olusjeh9d6hnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elgivesv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIG9W84hBycSJwZr86wxpY_lkRq8StZkk',
    appId: '1:63376358868:web:cfc8adc1022e010f97ea41',
    messagingSenderId: '63376358868',
    projectId: 'cmsc-23-project-4cdeb',
    authDomain: 'cmsc-23-project-4cdeb.firebaseapp.com',
    storageBucket: 'cmsc-23-project-4cdeb.appspot.com',
  );

}